<<<<<<< HEAD
# Generated by Django 4.2.1 on 2023-06-14 18:56
=======
# Generated by Django 4.1.4 on 2023-06-15 14:24
>>>>>>> 2e4425d38e9be923af87dec9e37b0a5dfabf454a

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Evenement',
            fields=[
                ('idEvenement', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=80)),
                ('Description', models.CharField(max_length=400)),
                ('DateDebut', models.DateField()),
                ('DateFin', models.DateField()),
                ('DatePublication', models.DateField(auto_now_add=True)),
=======
            name="Evenement",
            fields=[
                ("idEvenement", models.AutoField(primary_key=True, serialize=False)),
                ("Nom", models.CharField(max_length=80)),
                ("Description", models.CharField(max_length=400)),
                ("DateDebut", models.DateField()),
                ("DateFin", models.DateField()),
                ("DatePublication", models.DateField(auto_now_add=True)),
>>>>>>> 2e4425d38e9be923af87dec9e37b0a5dfabf454a
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
<<<<<<< HEAD
                ('idRegion', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(default='', max_length=50)),
=======
                ("idRegion", models.AutoField(primary_key=True, serialize=False)),
                ("designation", models.CharField(default="", max_length=50)),
>>>>>>> 2e4425d38e9be923af87dec9e37b0a5dfabf454a
            ],
        ),
        migrations.CreateModel(
            name="Visiteur",
            fields=[
                ("idVisiteur", models.AutoField(primary_key=True, serialize=False)),
                ("Nom", models.CharField(max_length=60)),
                ("Prenom", models.CharField(max_length=60, null=True)),
                ("Pays", models.CharField(max_length=45)),
                ("NumTel", models.CharField(max_length=10, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("motDePasse", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="VisiteurAuth",
            fields=[
                ("idauth", models.AutoField(primary_key=True, serialize=False)),
                ("Nom", models.CharField(max_length=60)),
                ("Prenom", models.CharField(max_length=60, null=True)),
                ("Pays", models.CharField(max_length=45)),
                ("NumTel", models.CharField(max_length=10, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("motDePasse", models.CharField(max_length=500)),
                ("token", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="PointInteret",
            fields=[
<<<<<<< HEAD
                ('idPoint', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=60)),
                ('description', models.CharField(default=' ', max_length=500)),
                ('longitude', models.FloatField(default=4)),
                ('latitude', models.FloatField(default=1)),
                ('jours', models.CharField(blank=True, choices=[('dimanche', 'Dimanche'), ('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi')], max_length=100)),
                ('heureOuverture', models.TimeField(default='00:00:00')),
                ('heureFermeture', models.TimeField(default='00:00:00')),
                ('rate', models.IntegerField(default=0)),
                ('categorie', models.CharField(default=' ', max_length=50)),
                ('theme', models.CharField(default='', max_length=50)),
                ('regionId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.region')),
            ],
        ),
        migrations.CreateModel(
            name='PiImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default=None, upload_to='images/')),
                ('piId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.pointinteret')),
=======
                ("idPoint", models.AutoField(primary_key=True, serialize=False)),
                ("Nom", models.CharField(max_length=60)),
                ("description", models.CharField(default=" ", max_length=500)),
                ("longitude", models.FloatField(default=4)),
                ("latitude", models.FloatField(default=1)),
                (
                    "jours",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dimanche", "Dimanche"),
                            ("lundi", "Lundi"),
                            ("mardi", "Mardi"),
                            ("mercredi", "Mercredi"),
                            ("jeudi", "Jeudi"),
                            ("vendredi", "Vendredi"),
                            ("samedi", "Samedi"),
                        ],
                        max_length=100,
                    ),
                ),
                ("heureOuverture", models.TimeField(default="00:00:00")),
                ("heureFermeture", models.TimeField(default="00:00:00")),
                ("rate", models.IntegerField(default=0)),
                ("categorie", models.CharField(default=" ", max_length=50)),
                ("theme", models.CharField(default="", max_length=50)),
                (
                    "regionId",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="backend.region",
                    ),
                ),
>>>>>>> 2e4425d38e9be923af87dec9e37b0a5dfabf454a
            ],
        ),
        migrations.CreateModel(
            name="PiImage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(default=None, upload_to="images/")),
                (
                    "piId",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.pointinteret",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='eventImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default=None, upload_to='images/')),
                ('eventId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.evenement')),
=======
            name="MoyenTransport",
            fields=[
                (
                    "idMoyenTransport",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=50)),
                ("NombrePassagers", models.IntegerField()),
                (
                    "PiId",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.pointinteret",
                    ),
                ),
>>>>>>> 2e4425d38e9be923af87dec9e37b0a5dfabf454a
            ],
        ),
        migrations.AddField(
            model_name='evenement',
            name='PiId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.pointinteret'),
        ),
        migrations.CreateModel(
            name="eventImage",
            fields=[
<<<<<<< HEAD
                ('idCommentaire', models.AutoField(primary_key=True, serialize=False)),
                ('Contenu', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('accept', models.BooleanField(default=False)),
                ('PiId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.pointinteret')),
                ('visiteurId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.visiteur')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('idAdmin', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=60)),
                ('Prenom', models.CharField(max_length=60, null=True)),
                ('NumTel', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('motDePasse', models.CharField(max_length=500)),
                ('regionId', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.region')),
=======
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(default=None, upload_to="images/")),
                (
                    "eventId",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.evenement",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="evenement",
            name="PiId",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.pointinteret",
            ),
        ),
        migrations.CreateModel(
            name="Commentaire",
            fields=[
                ("idCommentaire", models.AutoField(primary_key=True, serialize=False)),
                ("Contenu", models.CharField(max_length=100)),
                ("date", models.DateField(auto_now_add=True)),
                ("accept", models.BooleanField(default=False)),
                (
                    "PiId",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.pointinteret",
                    ),
                ),
                (
                    "visiteurId",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.visiteur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("idAdmin", models.AutoField(primary_key=True, serialize=False)),
                ("Nom", models.CharField(max_length=60)),
                ("Prenom", models.CharField(max_length=60, null=True)),
                ("NumTel", models.CharField(max_length=10, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("motDePasse", models.CharField(max_length=500)),
                (
                    "regionId",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="backend.region",
                    ),
                ),
>>>>>>> 2e4425d38e9be923af87dec9e37b0a5dfabf454a
            ],
        ),
    ]
