# Generated by Django 4.2.1 on 2023-06-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
