# Generated by Django 4.1.4 on 2023-06-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointinteret",
            name="transports",
            field=models.ManyToManyField(to="backend.moyentransport"),
        ),
        migrations.AddField(
            model_name="region",
            name="xcoor",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="region",
            name="ycoor",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="region",
            name="zoom",
            field=models.IntegerField(default=5),
        ),
    ]
