# Generated by Django 4.2.1 on 2023-06-14 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_commentaire_accept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointinteret',
            name='adminId',
        ),
        migrations.AddField(
            model_name='pointinteret',
            name='regionId',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.region'),
        ),
    ]
