# Generated by Django 4.1.4 on 2023-05-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_visiteur_motdepasse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiteur',
            name='Prenom',
            field=models.CharField(default='Null', max_length=60),
        ),
    ]
