# Generated by Django 4.1.4 on 2023-06-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_pointinteret_transports_region_xcoor_region_ycoor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moyentransport",
            name="PiId",
        ),
    ]
