# Generated by Django 4.2.1 on 2023-06-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_pointinteret_regionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='designation',
            field=models.CharField(default='', max_length=50),
        ),
    ]
