# Generated by Django 4.1.4 on 2023-05-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_visiteur_numtel_alter_visiteur_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointinteret',
            name='heureOuverture',
            field=models.TimeField(),
        ),
    ]
