# Generated by Django 4.2.1 on 2023-06-14 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_region_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default=None, upload_to='images/')),
                ('piId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.pointinteret')),
            ],
        ),
        migrations.CreateModel(
            name='eventImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default=None, upload_to='images/')),
                ('eventId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.evenement')),
            ],
        ),
    ]
