# Generated by Django 4.1.4 on 2023-05-24 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_moyentransport_piid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moyentransport',
            old_name='idMoyenTrasport',
            new_name='idMoyenTransport',
        ),
    ]
