# Generated by Django 4.1.4 on 2023-05-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_idmoyentrasport_moyentransport_idmoyentransport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='DatePublication',
            field=models.DateField(auto_now_add=True),
        ),
    ]
