# Generated by Django 4.1.4 on 2023-06-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0008_alter_commentaire_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="Nom",
            field=models.CharField(default="", max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="region",
            name="xcoor",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="region",
            name="ycoor",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="region",
            name="zoom",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
