# Generated by Django 4.1.4 on 2023-06-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0009_region_nom_region_xcoor_region_ycoor_region_zoom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moyentransport",
            name="PiId",
        ),
        migrations.AddField(
            model_name="commentaire",
            name="transports",
            field=models.ManyToManyField(to="backend.moyentransport"),
        ),
    ]
