# Generated by Django 4.1.4 on 2023-06-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0010_remove_moyentransport_piid_commentaire_transports"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commentaire",
            name="transports",
        ),
        migrations.AddField(
            model_name="pointinteret",
            name="transports",
            field=models.ManyToManyField(to="backend.moyentransport"),
        ),
    ]
